### ISSUE TITLE
Met a problem to install pgml-dashboard

### ISSUE THREAD

**Issue by SeptSky** [postgresml/postgresml#779] opened 2023-06-24 15:19 UTC
I have succeeded to install postgres-pgml-15(v2.6.0) on WSL2 Ubuntu 22.04 OS. Then when I was installing pgml-dashboard, I met a problem described below:
 xxx@yyy:/tmp/postgresml/pgml-dashboard$ cargo run
   Compiling pgml-dashboard v2.6.0 (/tmp/postgresml/pgml-dashboard)
error: failed to run custom build command for `pgml-dashboard v2.6.0 (/tmp/postgresml/pgml-dashboard)`

Caused by:
  process didn't exit successfully: `/tmp/postgresml/pgml-dashboard/target/debug/build/pgml-dashboard-4edf65d866a2d87e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=migrations
  cargo:rustc-env=GIT_SHA=545ccb613413eab4751bf03ea4c020c09b20af3c

  SCSS compilation failed to run

  --- stderr
  /usr/bin/env: ‘bash\r’: No such file or directory
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:29:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

I have no any idea to sovle that problem.

**Comment by montanalow** [comment] 2023-06-24 22:01
`bash\r` looks like we have the wrong line ending in that file, or else your git is configured to use windows line endings ("\r\n") instead of just "\n". Can you replace that line ending and let me know if that fixes your problem? All files in this repo should be checked in with Unix line endings only.

**Comment by SeptSky** [comment] 2023-06-25 02:51
> `bash\r` looks like we have the wrong line ending in that file, or else your git is configured to use windows line endings ("\r\n") instead of just "\n". Can you replace that line ending and let me know if that fixes your problem? All files in this repo should be checked in with Unix line endings only.

The file "/usr/bin/env" exists, but it's a binary file. My git is preinstalled with WSL2 Ubuntu 22.04, I have compiled and installed the pgml extension successfully with the same git command, and I didn't change any git config info. My OS was upgraded from 20.04 to 22.04.

**Comment by montanalow** [comment] 2023-06-25 02:59
I'm not sure if the issue is in your git config, or the file's line ending encoding, but since the current file encodings seem to work for most people, I'm assuming this is an issue with your git config. Can you try converting the file's line endings, and checking that your git config line endings are unix style?

**Comment by SeptSky** [comment] 2023-06-25 03:24
> I'm not sure if the issue is in your git config, or the file's line ending encoding, but since the current file encodings seem to work for most people, I'm assuming this is an issue with your git config. Can you try converting the file's line endings, and checking that your git config line endings are unix style?

I ran git config --list command, there's an empty message displayed. I will try again with another OS environment. Thanks for your help.

**Comment by SeptSky** [comment] 2023-06-25 14:55
I have reinstalled Unbuntu 22.04 on VMware, and pgml extension has been installed successfully. But when I reinstall pgml-dashboard, it occurred another issue:

xxx@xxx-vm:~/postgresml/pgml-dashboard$ cargo run
   Compiling pgml-dashboard v2.6.0 (/home/hwq/postgresml/pgml-dashboard)
error: failed to run custom build command for `pgml-dashboard v2.6.0 (/home/xxx/postgresml/pgml-dashboard)`

Caused by:
  process didn't exit successfully: `/home/hwq/postgresml/pgml-dashboard/target/debug/build/pgml-dashboard-4edf65d866a2d87e/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=migrations
  cargo:rustc-env=GIT_SHA=f7ad1879473b5e2fe37f2891c20a4eb75f5b5c51


  --- stderr
  thread 'main' panicked at '`npm exec sass` failed: Os { code: 2, kind: NotFound, message: "No such file or directory" }', build.rs:21:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

The message 'npm exec sass' seems to be the key, but how to resolve it?

**Comment by levkk** [comment] 2023-06-25 16:04
```
npm install -g sass
```

Dockerfile for Ubuntu 22.04 [here](https://github.com/postgresml/postgresml/blob/master/pgml-dashboard/Dockerfile).

**Comment by SeptSky** [comment] 2023-06-25 23:19
> ```
> npm install -g sass
> ```
> 
> Dockerfile for Debian [here](https://github.com/postgresml/postgresml/blob/master/pgml-dashboard/Dockerfile).
> 
> Then to build and run the dashboard, do
> 
> ```
> export DATABASE_URL=postgres://user:password@host:port/database_where_pgml_is_already_installed
> cargo sqlx migrate run
> cargo run
> ```

According to your guidance, I finally completed the installation. After open the url "localhost:8000", I saw the pgml-dashboard web page.  Thank you so much for your help!

**Closed** 2023-06-26 02:42 UTC
